import { getOpenAI } from "@/lib/openai/client";
import { marketplaceAgentsById, toOpenAITools, type AgentRunInput } from "@/lib/ai/agent-definitions";

export type AgentRunResult = {
  answer: string;
  recommendedActions: string[];
  toolPlan: Array<{ tool: string; reason: string; arguments?: Record<string, unknown> }>;
  safetyFlags: string[];
  memoryUpdates: string[];
  auditSummary: string;
  model: string;
  fallback: boolean;
  raw?: unknown;
  tokenUsage?: Record<string, unknown> | null;
};

function fallbackRun(input: AgentRunInput): AgentRunResult {
  const agent = marketplaceAgentsById[input.agent];
  const toolPlan = agent.tools.slice(0, 3).map((tool) => ({
    tool: tool.name,
    reason: tool.description,
    arguments: input.context?.listingId ? { listingId: input.context.listingId } : undefined
  }));

  return {
    answer: `${agent.name} is configured. Add OPENAI_API_KEY to generate live model responses. Based on your request, I would first clarify missing marketplace facts, then use the proposed tool plan under the agent's permissions before recommending a confirmed next step.`,
    recommendedActions: ["Review the proposed tool plan", "Confirm any write or escalation action before execution", "Provide listing, conversation, or transaction IDs if relevant"],
    toolPlan,
    safetyFlags: [],
    memoryUpdates: [],
    auditSummary: `Fallback response for ${agent.id}; no OpenAI request was sent.`,
    model: "fallback-local",
    fallback: true
  };
}

function normalizeArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.map((item) => String(item)).filter(Boolean);
}

function normalizeToolPlan(value: unknown): AgentRunResult["toolPlan"] {
  if (!Array.isArray(value)) return [];
  return value.map((item) => {
    if (typeof item === "string") return { tool: item, reason: "Model-proposed tool." };
    if (item && typeof item === "object") {
      const record = item as Record<string, unknown>;
      return {
        tool: String(record.tool ?? record.name ?? "unknown_tool"),
        reason: String(record.reason ?? record.description ?? "Model-proposed tool."),
        arguments: record.arguments && typeof record.arguments === "object" ? (record.arguments as Record<string, unknown>) : undefined
      };
    }
    return { tool: "unknown_tool", reason: "Model-proposed tool." };
  });
}

export async function runMarketplaceAgent(input: AgentRunInput): Promise<AgentRunResult> {
  const agent = marketplaceAgentsById[input.agent];
  const model = "gpt-4o-mini";
  const completion = await getOpenAI().chat.completions.create({
    model,
    response_format: { type: "json_object" },
    tools: toOpenAITools(agent),
    tool_choice: "none",
    messages: [
      { role: "system", content: agent.systemPrompt },
      {
        role: "user",
        content: JSON.stringify({
          message: input.message,
          context: input.context ?? {},
          availableTools: agent.tools.map((tool) => ({ name: tool.name, permission: tool.permission, databaseAccess: tool.databaseAccess }))
        })
      }
    ]
  });

  const content = completion.choices[0]?.message.content ?? "{}";
  const parsed = JSON.parse(content) as Record<string, unknown>;

  return {
    answer: String(parsed.answer ?? "I could not generate a response."),
    recommendedActions: normalizeArray(parsed.recommendedActions),
    toolPlan: normalizeToolPlan(parsed.toolPlan),
    safetyFlags: normalizeArray(parsed.safetyFlags),
    memoryUpdates: normalizeArray(parsed.memoryUpdates),
    auditSummary: String(parsed.auditSummary ?? `OpenAI response generated by ${agent.id}.`),
    model,
    fallback: false,
    raw: parsed,
    tokenUsage: completion.usage ? { ...completion.usage } : null
  };
}
