-- Complete Supabase Postgres schema for the Friction-Free Marketplace.
-- This migration creates the core marketplace data model, constraints, indexes,
-- foreign keys, updated_at triggers, and row level security policies.

begin;

create extension if not exists pgcrypto;
create extension if not exists citext;

-- -----------------------------------------------------------------------------
-- Shared helpers
-- -----------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- -----------------------------------------------------------------------------
-- Enumerated types
-- -----------------------------------------------------------------------------

do $$
begin
  create type public.user_role as enum ('buyer', 'seller', 'admin', 'super_admin');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.user_status as enum ('pending', 'active', 'suspended', 'banned', 'deleted');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.address_type as enum ('shipping', 'billing', 'pickup', 'return', 'business');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.listing_status as enum ('draft', 'active', 'reserved', 'sold', 'paused', 'expired', 'removed');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.media_status as enum ('pending', 'ready', 'rejected', 'deleted');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.offer_status as enum ('pending', 'accepted', 'countered', 'declined', 'expired', 'withdrawn');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.transaction_status as enum ('pending_payment', 'paid', 'escrowed', 'shipped', 'delivered', 'completed', 'cancelled', 'refunded', 'disputed');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.payment_status as enum ('requires_action', 'authorized', 'captured', 'held', 'released', 'refunded', 'failed', 'cancelled');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.payout_status as enum ('pending', 'processing', 'paid', 'failed', 'cancelled');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.report_status as enum ('open', 'triaged', 'investigating', 'actioned', 'dismissed', 'closed');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.dispute_status as enum ('opened', 'awaiting_buyer', 'awaiting_seller', 'under_review', 'resolved_buyer', 'resolved_seller', 'closed');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.notification_status as enum ('queued', 'sent', 'read', 'failed', 'archived');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.ai_task_status as enum ('queued', 'running', 'succeeded', 'failed', 'cancelled');
exception when duplicate_object then null;
end $$;

-- -----------------------------------------------------------------------------
-- Identity, profiles, addresses, and trust
-- -----------------------------------------------------------------------------

create table if not exists public.verification_levels (
  id smallint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  rank integer not null unique check (rank >= 0),
  requirements jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email citext unique,
  phone text,
  role public.user_role not null default 'buyer',
  status public.user_status not null default 'pending',
  verification_level_id smallint references public.verification_levels(id) on delete set null,
  last_sign_in_at timestamptz,
  banned_reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint users_email_or_phone check (email is not null or phone is not null)
);

create table if not exists public.profiles (
  user_id uuid primary key references public.users(id) on delete cascade,
  display_name text not null check (length(display_name) between 2 and 80),
  username citext unique check (username ~ '^[a-zA-Z0-9_][a-zA-Z0-9_.-]{2,29}$'),
  bio text check (length(bio) <= 1000),
  avatar_url text,
  banner_url text,
  location_label text,
  website_url text,
  seller_headline text,
  response_time_minutes integer check (response_time_minutes >= 0),
  preferences jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  type public.address_type not null,
  name text,
  line1 text not null,
  line2 text,
  city text not null,
  state_region text,
  postal_code text,
  country_code char(2) not null check (country_code ~ '^[A-Z]{2}$'),
  latitude numeric(9,6),
  longitude numeric(9,6),
  is_default boolean not null default false,
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint addresses_lat_lng_pair check ((latitude is null and longitude is null) or (latitude is not null and longitude is not null))
);

-- -----------------------------------------------------------------------------
-- Catalog and listings
-- -----------------------------------------------------------------------------

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  parent_id uuid references public.categories(id) on delete set null,
  slug citext not null unique,
  name text not null,
  description text,
  icon_url text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.listings (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.users(id) on delete cascade,
  category_id uuid references public.categories(id) on delete set null,
  title text not null check (length(title) between 3 and 160),
  slug citext unique,
  description text not null,
  condition text,
  status public.listing_status not null default 'draft',
  price_amount numeric(12,2) not null check (price_amount >= 0),
  currency char(3) not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  quantity integer not null default 1 check (quantity >= 0),
  location_city text,
  location_region text,
  location_country char(2) check (location_country is null or location_country ~ '^[A-Z]{2}$'),
  ships_to text[] not null default array[]::text[],
  pickup_available boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  published_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  search_vector tsvector generated always as (
    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(description, '')), 'B')
  ) stored
);

create table if not exists public.listing_images (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  storage_path text not null,
  public_url text,
  alt_text text,
  width integer check (width is null or width > 0),
  height integer check (height is null or height > 0),
  sort_order integer not null default 0,
  status public.media_status not null default 'pending',
  moderation_result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.listing_videos (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  storage_path text not null,
  thumbnail_url text,
  duration_seconds integer check (duration_seconds is null or duration_seconds >= 0),
  sort_order integer not null default 0,
  status public.media_status not null default 'pending',
  moderation_result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.listing_attributes (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  name text not null,
  value text not null,
  value_number numeric,
  unit text,
  created_at timestamptz not null default now(),
  constraint listing_attributes_unique_name unique (listing_id, name)
);

create table if not exists public.favorites (
  user_id uuid not null references public.users(id) on delete cascade,
  listing_id uuid not null references public.listings(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, listing_id)
);

create table if not exists public.saved_searches (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  query text,
  filters jsonb not null default '{}'::jsonb,
  alert_enabled boolean not null default true,
  alert_frequency text not null default 'instant' check (alert_frequency in ('instant', 'daily', 'weekly', 'never')),
  last_notified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Messaging, offers, transactions, escrow, payouts, and reviews
-- -----------------------------------------------------------------------------

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid references public.listings(id) on delete set null,
  buyer_id uuid not null references public.users(id) on delete cascade,
  seller_id uuid not null references public.users(id) on delete cascade,
  status text not null default 'open' check (status in ('open', 'archived', 'blocked', 'closed')),
  last_message_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint conversations_distinct_participants check (buyer_id <> seller_id)
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.users(id) on delete cascade,
  body text not null check (length(body) <= 10000),
  attachments jsonb not null default '[]'::jsonb,
  moderation_status text not null default 'pending' check (moderation_status in ('pending', 'approved', 'flagged', 'removed')),
  read_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.offers (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  buyer_id uuid not null references public.users(id) on delete cascade,
  seller_id uuid not null references public.users(id) on delete cascade,
  amount numeric(12,2) not null check (amount >= 0),
  currency char(3) not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  message text,
  status public.offer_status not null default 'pending',
  parent_offer_id uuid references public.offers(id) on delete set null,
  expires_at timestamptz,
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint offers_distinct_participants check (buyer_id <> seller_id)
);

create table if not exists public.transactions (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid references public.listings(id) on delete set null,
  offer_id uuid unique references public.offers(id) on delete set null,
  buyer_id uuid not null references public.users(id) on delete restrict,
  seller_id uuid not null references public.users(id) on delete restrict,
  status public.transaction_status not null default 'pending_payment',
  item_amount numeric(12,2) not null check (item_amount >= 0),
  shipping_amount numeric(12,2) not null default 0 check (shipping_amount >= 0),
  tax_amount numeric(12,2) not null default 0 check (tax_amount >= 0),
  marketplace_fee_amount numeric(12,2) not null default 0 check (marketplace_fee_amount >= 0),
  total_amount numeric(12,2) generated always as (item_amount + shipping_amount + tax_amount + marketplace_fee_amount) stored,
  currency char(3) not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  shipping_address_id uuid references public.addresses(id) on delete set null,
  tracking_number text,
  carrier text,
  paid_at timestamptz,
  shipped_at timestamptz,
  delivered_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint transactions_distinct_participants check (buyer_id <> seller_id)
);

create table if not exists public.escrow_payments (
  id uuid primary key default gen_random_uuid(),
  transaction_id uuid not null unique references public.transactions(id) on delete cascade,
  provider text not null,
  provider_payment_id text not null unique,
  status public.payment_status not null default 'requires_action',
  amount numeric(12,2) not null check (amount >= 0),
  currency char(3) not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  authorized_at timestamptz,
  captured_at timestamptz,
  held_at timestamptz,
  released_at timestamptz,
  refunded_at timestamptz,
  failure_code text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payouts (
  id uuid primary key default gen_random_uuid(),
  transaction_id uuid not null references public.transactions(id) on delete cascade,
  seller_id uuid not null references public.users(id) on delete restrict,
  provider text not null,
  provider_payout_id text unique,
  status public.payout_status not null default 'pending',
  amount numeric(12,2) not null check (amount >= 0),
  currency char(3) not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  scheduled_at timestamptz,
  paid_at timestamptz,
  failure_code text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  transaction_id uuid not null references public.transactions(id) on delete cascade,
  reviewer_id uuid not null references public.users(id) on delete cascade,
  reviewee_id uuid not null references public.users(id) on delete cascade,
  listing_id uuid references public.listings(id) on delete set null,
  rating smallint not null check (rating between 1 and 5),
  title text,
  body text check (body is null or length(body) <= 5000),
  is_public boolean not null default true,
  status text not null default 'published' check (status in ('pending', 'published', 'hidden', 'removed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reviews_one_per_reviewer_transaction unique (transaction_id, reviewer_id),
  constraint reviews_distinct_participants check (reviewer_id <> reviewee_id)
);

create table if not exists public.trust_scores (
  user_id uuid primary key references public.users(id) on delete cascade,
  score numeric(5,2) not null default 0 check (score between 0 and 100),
  seller_score numeric(5,2) not null default 0 check (seller_score between 0 and 100),
  buyer_score numeric(5,2) not null default 0 check (buyer_score between 0 and 100),
  review_count integer not null default 0 check (review_count >= 0),
  completed_transactions integer not null default 0 check (completed_transactions >= 0),
  dispute_rate numeric(5,4) not null default 0 check (dispute_rate between 0 and 1),
  fraud_risk_level text not null default 'low' check (fraud_risk_level in ('low', 'medium', 'high', 'critical')),
  computed_at timestamptz not null default now(),
  model_version text not null default 'v1',
  signals jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Trust, safety, notifications, AI, analytics, and audit
-- -----------------------------------------------------------------------------

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid references public.users(id) on delete set null,
  reported_user_id uuid references public.users(id) on delete set null,
  listing_id uuid references public.listings(id) on delete set null,
  message_id uuid references public.messages(id) on delete set null,
  reason text not null,
  description text,
  status public.report_status not null default 'open',
  assigned_admin_id uuid references public.users(id) on delete set null,
  resolution text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  constraint reports_has_subject check (reported_user_id is not null or listing_id is not null or message_id is not null)
);

create table if not exists public.disputes (
  id uuid primary key default gen_random_uuid(),
  transaction_id uuid not null references public.transactions(id) on delete cascade,
  opened_by_id uuid not null references public.users(id) on delete cascade,
  assigned_admin_id uuid references public.users(id) on delete set null,
  reason text not null,
  description text,
  status public.dispute_status not null default 'opened',
  resolution text,
  evidence jsonb not null default '[]'::jsonb,
  opened_at timestamptz not null default now(),
  due_at timestamptz,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.fraud_signals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete cascade,
  listing_id uuid references public.listings(id) on delete cascade,
  transaction_id uuid references public.transactions(id) on delete cascade,
  signal_type text not null,
  risk_score numeric(5,2) not null check (risk_score between 0 and 100),
  source text not null,
  payload jsonb not null default '{}'::jsonb,
  reviewed_by uuid references public.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint fraud_signals_has_subject check (user_id is not null or listing_id is not null or transaction_id is not null)
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null,
  title text not null,
  body text,
  channel text not null default 'in_app' check (channel in ('in_app', 'email', 'sms', 'push')),
  status public.notification_status not null default 'queued',
  action_url text,
  payload jsonb not null default '{}'::jsonb,
  sent_at timestamptz,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_agents (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid references public.users(id) on delete cascade,
  name text not null,
  agent_type text not null check (agent_type in ('buyer', 'seller', 'support', 'moderation', 'pricing', 'search')),
  status text not null default 'active' check (status in ('active', 'paused', 'disabled', 'deleted')),
  instructions text,
  permissions jsonb not null default '{}'::jsonb,
  configuration jsonb not null default '{}'::jsonb,
  last_run_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_tasks (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid not null references public.ai_agents(id) on delete cascade,
  requested_by uuid references public.users(id) on delete set null,
  task_type text not null,
  status public.ai_task_status not null default 'queued',
  input jsonb not null default '{}'::jsonb,
  output jsonb,
  error_message text,
  scheduled_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.search_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete set null,
  session_id text,
  query text,
  filters jsonb not null default '{}'::jsonb,
  result_count integer check (result_count is null or result_count >= 0),
  clicked_listing_id uuid references public.listings(id) on delete set null,
  ip_hash text,
  user_agent text,
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete set null,
  session_id text,
  event_name text not null,
  entity_type text,
  entity_id uuid,
  properties jsonb not null default '{}'::jsonb,
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_actions (
  id uuid primary key default gen_random_uuid(),
  admin_id uuid not null references public.users(id) on delete restrict,
  action_type text not null,
  target_type text not null,
  target_id uuid,
  reason text,
  before_state jsonb,
  after_state jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references public.users(id) on delete set null,
  actor_type text not null default 'user' check (actor_type in ('user', 'admin', 'system', 'ai_agent')),
  action text not null,
  table_name text,
  record_id uuid,
  ip_hash text,
  user_agent text,
  old_values jsonb,
  new_values jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users u
    where u.id = auth.uid()
      and u.role in ('admin', 'super_admin')
      and u.status = 'active'
  );
$$;

create or replace function public.is_conversation_participant(conversation_uuid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.conversations c
    where c.id = conversation_uuid
      and auth.uid() in (c.buyer_id, c.seller_id)
  );
$$;

create or replace function public.is_transaction_participant(transaction_uuid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.transactions t
    where t.id = transaction_uuid
      and auth.uid() in (t.buyer_id, t.seller_id)
  );
$$;

-- -----------------------------------------------------------------------------
-- Updated-at triggers
-- -----------------------------------------------------------------------------

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'verification_levels','users','profiles','addresses','categories','listings',
    'listing_images','listing_videos','saved_searches','conversations','messages',
    'offers','transactions','escrow_payments','payouts','reviews','trust_scores',
    'reports','disputes','notifications','ai_agents','ai_tasks'
  ] loop
    execute format('drop trigger if exists set_%I_updated_at on public.%I', table_name, table_name);
    execute format('create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()', table_name, table_name);
  end loop;
end $$;

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

create index if not exists users_status_created_idx on public.users(status, created_at desc);
create index if not exists users_verification_level_idx on public.users(verification_level_id);
create index if not exists users_active_email_idx on public.users(email) where deleted_at is null;

create index if not exists profiles_username_idx on public.profiles(username);
create index if not exists addresses_user_type_idx on public.addresses(user_id, type);
create unique index if not exists addresses_one_default_per_type_idx on public.addresses(user_id, type) where is_default;

create index if not exists categories_parent_sort_idx on public.categories(parent_id, sort_order);
create index if not exists categories_active_idx on public.categories(is_active, sort_order);

create index if not exists listings_seller_status_idx on public.listings(seller_id, status, created_at desc);
create index if not exists listings_category_status_idx on public.listings(category_id, status, created_at desc);
create index if not exists listings_price_idx on public.listings(currency, price_amount);
create index if not exists listings_published_idx on public.listings(published_at desc) where status = 'active' and deleted_at is null;
create index if not exists listings_search_vector_idx on public.listings using gin(search_vector);
create index if not exists listings_metadata_gin_idx on public.listings using gin(metadata);

create index if not exists listing_images_listing_sort_idx on public.listing_images(listing_id, sort_order);
create index if not exists listing_videos_listing_sort_idx on public.listing_videos(listing_id, sort_order);
create index if not exists listing_attributes_listing_idx on public.listing_attributes(listing_id);
create index if not exists listing_attributes_name_value_idx on public.listing_attributes(name, value);

create index if not exists favorites_listing_idx on public.favorites(listing_id, created_at desc);
create index if not exists saved_searches_user_idx on public.saved_searches(user_id, updated_at desc);

create index if not exists conversations_buyer_idx on public.conversations(buyer_id, updated_at desc);
create index if not exists conversations_seller_idx on public.conversations(seller_id, updated_at desc);
create index if not exists conversations_listing_idx on public.conversations(listing_id);
create unique index if not exists conversations_unique_open_listing_pair_idx on public.conversations(listing_id, buyer_id, seller_id) where status = 'open';
create index if not exists messages_conversation_created_idx on public.messages(conversation_id, created_at desc);
create index if not exists messages_sender_idx on public.messages(sender_id, created_at desc);

create index if not exists offers_listing_status_idx on public.offers(listing_id, status, created_at desc);
create index if not exists offers_buyer_status_idx on public.offers(buyer_id, status, created_at desc);
create index if not exists offers_seller_status_idx on public.offers(seller_id, status, created_at desc);
create index if not exists transactions_buyer_status_idx on public.transactions(buyer_id, status, created_at desc);
create index if not exists transactions_seller_status_idx on public.transactions(seller_id, status, created_at desc);
create index if not exists transactions_listing_idx on public.transactions(listing_id);
create index if not exists escrow_payments_status_idx on public.escrow_payments(status, created_at desc);
create index if not exists payouts_seller_status_idx on public.payouts(seller_id, status, created_at desc);
create index if not exists reviews_reviewee_idx on public.reviews(reviewee_id, status, created_at desc);
create index if not exists reviews_listing_idx on public.reviews(listing_id, created_at desc);
create index if not exists trust_scores_score_idx on public.trust_scores(score desc, computed_at desc);

create index if not exists reports_status_idx on public.reports(status, created_at desc);
create index if not exists reports_reporter_idx on public.reports(reporter_id, created_at desc);
create index if not exists disputes_transaction_idx on public.disputes(transaction_id, status);
create index if not exists disputes_status_idx on public.disputes(status, created_at desc);
create index if not exists fraud_signals_user_idx on public.fraud_signals(user_id, created_at desc);
create index if not exists fraud_signals_risk_idx on public.fraud_signals(risk_score desc, created_at desc);
create index if not exists notifications_user_status_idx on public.notifications(user_id, status, created_at desc);
create index if not exists ai_agents_owner_idx on public.ai_agents(owner_user_id, status);
create index if not exists ai_tasks_agent_status_idx on public.ai_tasks(agent_id, status, created_at desc);
create index if not exists search_events_user_created_idx on public.search_events(user_id, created_at desc);
create index if not exists search_events_query_idx on public.search_events using gin(to_tsvector('english', coalesce(query, '')));
create index if not exists analytics_events_name_created_idx on public.analytics_events(event_name, created_at desc);
create index if not exists analytics_events_user_created_idx on public.analytics_events(user_id, created_at desc);
create index if not exists admin_actions_admin_created_idx on public.admin_actions(admin_id, created_at desc);
create index if not exists admin_actions_target_idx on public.admin_actions(target_type, target_id);
create index if not exists audit_logs_actor_created_idx on public.audit_logs(actor_id, created_at desc);
create index if not exists audit_logs_record_idx on public.audit_logs(table_name, record_id, created_at desc);

-- -----------------------------------------------------------------------------
-- Row level security and policies
-- -----------------------------------------------------------------------------

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'verification_levels','users','profiles','addresses','categories','listings',
    'listing_images','listing_videos','listing_attributes','favorites','saved_searches',
    'conversations','messages','offers','transactions','escrow_payments','payouts',
    'reviews','trust_scores','reports','disputes','fraud_signals','notifications',
    'ai_agents','ai_tasks','search_events','analytics_events','admin_actions','audit_logs'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
  end loop;
end $$;

-- Public reference data.
create policy verification_levels_public_read on public.verification_levels for select using (true);
create policy verification_levels_admin_write on public.verification_levels for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());
create policy categories_public_read on public.categories for select using (is_active or public.current_user_is_admin());
create policy categories_admin_write on public.categories for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

-- Users and profiles.
create policy users_self_or_admin_read on public.users for select using (id = auth.uid() or public.current_user_is_admin());
create policy users_self_insert on public.users for insert with check (id = auth.uid());
create policy users_admin_update on public.users for update using (public.current_user_is_admin()) with check (public.current_user_is_admin());

create policy profiles_public_read on public.profiles for select using (true);
create policy profiles_self_insert on public.profiles for insert with check (user_id = auth.uid());
create policy profiles_self_update on public.profiles for update using (user_id = auth.uid() or public.current_user_is_admin()) with check (user_id = auth.uid() or public.current_user_is_admin());
create policy profiles_self_delete on public.profiles for delete using (user_id = auth.uid() or public.current_user_is_admin());

create policy addresses_owner_crud on public.addresses for all using (user_id = auth.uid() or public.current_user_is_admin()) with check (user_id = auth.uid() or public.current_user_is_admin());

-- Listings and media.
create policy listings_public_active_read on public.listings for select using ((status = 'active' and deleted_at is null) or seller_id = auth.uid() or public.current_user_is_admin());
create policy listings_seller_insert on public.listings for insert with check (seller_id = auth.uid() or public.current_user_is_admin());
create policy listings_seller_update on public.listings for update using (seller_id = auth.uid() or public.current_user_is_admin()) with check (seller_id = auth.uid() or public.current_user_is_admin());
create policy listings_seller_delete on public.listings for delete using (seller_id = auth.uid() or public.current_user_is_admin());

create policy listing_images_read on public.listing_images for select using (exists (select 1 from public.listings l where l.id = listing_id and ((l.status = 'active' and l.deleted_at is null) or l.seller_id = auth.uid() or public.current_user_is_admin())));
create policy listing_images_seller_write on public.listing_images for all using (exists (select 1 from public.listings l where l.id = listing_id and (l.seller_id = auth.uid() or public.current_user_is_admin()))) with check (exists (select 1 from public.listings l where l.id = listing_id and (l.seller_id = auth.uid() or public.current_user_is_admin())));

create policy listing_videos_read on public.listing_videos for select using (exists (select 1 from public.listings l where l.id = listing_id and ((l.status = 'active' and l.deleted_at is null) or l.seller_id = auth.uid() or public.current_user_is_admin())));
create policy listing_videos_seller_write on public.listing_videos for all using (exists (select 1 from public.listings l where l.id = listing_id and (l.seller_id = auth.uid() or public.current_user_is_admin()))) with check (exists (select 1 from public.listings l where l.id = listing_id and (l.seller_id = auth.uid() or public.current_user_is_admin())));

create policy listing_attributes_read on public.listing_attributes for select using (exists (select 1 from public.listings l where l.id = listing_id and ((l.status = 'active' and l.deleted_at is null) or l.seller_id = auth.uid() or public.current_user_is_admin())));
create policy listing_attributes_seller_write on public.listing_attributes for all using (exists (select 1 from public.listings l where l.id = listing_id and (l.seller_id = auth.uid() or public.current_user_is_admin()))) with check (exists (select 1 from public.listings l where l.id = listing_id and (l.seller_id = auth.uid() or public.current_user_is_admin())));

create policy favorites_owner_crud on public.favorites for all using (user_id = auth.uid() or public.current_user_is_admin()) with check (user_id = auth.uid() or public.current_user_is_admin());
create policy saved_searches_owner_crud on public.saved_searches for all using (user_id = auth.uid() or public.current_user_is_admin()) with check (user_id = auth.uid() or public.current_user_is_admin());

-- Messaging and commerce workflows.
create policy conversations_participant_read on public.conversations for select using (auth.uid() in (buyer_id, seller_id) or public.current_user_is_admin());
create policy conversations_buyer_insert on public.conversations for insert with check (buyer_id = auth.uid() or seller_id = auth.uid() or public.current_user_is_admin());
create policy conversations_participant_update on public.conversations for update using (auth.uid() in (buyer_id, seller_id) or public.current_user_is_admin()) with check (auth.uid() in (buyer_id, seller_id) or public.current_user_is_admin());

create policy messages_participant_read on public.messages for select using (public.is_conversation_participant(conversation_id) or public.current_user_is_admin());
create policy messages_participant_insert on public.messages for insert with check ((sender_id = auth.uid() and public.is_conversation_participant(conversation_id)) or public.current_user_is_admin());
create policy messages_sender_update on public.messages for update using (sender_id = auth.uid() or public.current_user_is_admin()) with check (sender_id = auth.uid() or public.current_user_is_admin());

create policy offers_participant_read on public.offers for select using (auth.uid() in (buyer_id, seller_id) or public.current_user_is_admin());
create policy offers_buyer_insert on public.offers for insert with check (buyer_id = auth.uid() or public.current_user_is_admin());
create policy offers_participant_update on public.offers for update using (auth.uid() in (buyer_id, seller_id) or public.current_user_is_admin()) with check (auth.uid() in (buyer_id, seller_id) or public.current_user_is_admin());

create policy transactions_participant_read on public.transactions for select using (auth.uid() in (buyer_id, seller_id) or public.current_user_is_admin());
create policy transactions_participant_insert on public.transactions for insert with check (auth.uid() in (buyer_id, seller_id) or public.current_user_is_admin());
create policy transactions_participant_update on public.transactions for update using (auth.uid() in (buyer_id, seller_id) or public.current_user_is_admin()) with check (auth.uid() in (buyer_id, seller_id) or public.current_user_is_admin());

create policy escrow_payments_participant_read on public.escrow_payments for select using (public.is_transaction_participant(transaction_id) or public.current_user_is_admin());
create policy escrow_payments_admin_write on public.escrow_payments for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

create policy payouts_seller_read on public.payouts for select using (seller_id = auth.uid() or public.current_user_is_admin());
create policy payouts_admin_write on public.payouts for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

create policy reviews_public_read on public.reviews for select using ((is_public and status = 'published') or reviewer_id = auth.uid() or reviewee_id = auth.uid() or public.current_user_is_admin());
create policy reviews_participant_insert on public.reviews for insert with check (reviewer_id = auth.uid() or public.current_user_is_admin());
create policy reviews_author_update on public.reviews for update using (reviewer_id = auth.uid() or public.current_user_is_admin()) with check (reviewer_id = auth.uid() or public.current_user_is_admin());

create policy trust_scores_public_read on public.trust_scores for select using (true);
create policy trust_scores_admin_write on public.trust_scores for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

-- Trust, safety, notifications, AI, analytics, and audit.
create policy reports_owner_or_admin_read on public.reports for select using (reporter_id = auth.uid() or reported_user_id = auth.uid() or public.current_user_is_admin());
create policy reports_user_insert on public.reports for insert with check (reporter_id = auth.uid() or public.current_user_is_admin());
create policy reports_admin_update on public.reports for update using (public.current_user_is_admin()) with check (public.current_user_is_admin());

create policy disputes_participant_read on public.disputes for select using (public.is_transaction_participant(transaction_id) or opened_by_id = auth.uid() or public.current_user_is_admin());
create policy disputes_participant_insert on public.disputes for insert with check (opened_by_id = auth.uid() or public.current_user_is_admin());
create policy disputes_admin_update on public.disputes for update using (public.current_user_is_admin()) with check (public.current_user_is_admin());

create policy fraud_signals_admin_read_write on public.fraud_signals for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());
create policy notifications_owner_crud on public.notifications for all using (user_id = auth.uid() or public.current_user_is_admin()) with check (user_id = auth.uid() or public.current_user_is_admin());

create policy ai_agents_owner_read on public.ai_agents for select using (owner_user_id = auth.uid() or public.current_user_is_admin());
create policy ai_agents_owner_write on public.ai_agents for all using (owner_user_id = auth.uid() or public.current_user_is_admin()) with check (owner_user_id = auth.uid() or public.current_user_is_admin());
create policy ai_tasks_owner_read on public.ai_tasks for select using (exists (select 1 from public.ai_agents a where a.id = agent_id and (a.owner_user_id = auth.uid() or public.current_user_is_admin())));
create policy ai_tasks_owner_write on public.ai_tasks for all using (exists (select 1 from public.ai_agents a where a.id = agent_id and (a.owner_user_id = auth.uid() or public.current_user_is_admin()))) with check (exists (select 1 from public.ai_agents a where a.id = agent_id and (a.owner_user_id = auth.uid() or public.current_user_is_admin())));

create policy search_events_owner_insert on public.search_events for insert with check (user_id is null or user_id = auth.uid() or public.current_user_is_admin());
create policy search_events_owner_or_admin_read on public.search_events for select using (user_id = auth.uid() or public.current_user_is_admin());
create policy analytics_events_insert on public.analytics_events for insert with check (user_id is null or user_id = auth.uid() or public.current_user_is_admin());
create policy analytics_events_admin_read on public.analytics_events for select using (public.current_user_is_admin());

create policy admin_actions_admin_only on public.admin_actions for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());
create policy audit_logs_admin_read on public.audit_logs for select using (public.current_user_is_admin());
create policy audit_logs_insert_admin_or_self on public.audit_logs for insert with check (actor_id = auth.uid() or public.current_user_is_admin() or actor_type in ('system', 'ai_agent'));

-- -----------------------------------------------------------------------------
-- Seed verification levels and base categories used by the application.
-- -----------------------------------------------------------------------------

insert into public.verification_levels (code, name, description, rank, requirements)
values
  ('unverified', 'Unverified', 'Email or phone account created; commerce activity is limited.', 0, '{}'::jsonb),
  ('basic', 'Basic', 'Verified email or phone with marketplace profile completed.', 10, '{"email_or_phone": true, "profile": true}'::jsonb),
  ('identity', 'Identity Verified', 'Government identity or equivalent KYC verification completed.', 20, '{"identity_document": true, "liveness": true}'::jsonb),
  ('trusted_seller', 'Trusted Seller', 'Identity verification plus successful selling history and low dispute rate.', 30, '{"identity": true, "completed_sales_min": 10, "max_dispute_rate": 0.02}'::jsonb)
on conflict (code) do update
set name = excluded.name,
    description = excluded.description,
    rank = excluded.rank,
    requirements = excluded.requirements,
    updated_at = now();

insert into public.categories (slug, name, description, sort_order)
values
  ('electronics', 'Electronics', 'Consumer electronics, devices, and accessories.', 10),
  ('home-garden', 'Home & Garden', 'Furniture, decor, tools, and garden items.', 20),
  ('fashion', 'Fashion', 'Clothing, shoes, watches, and accessories.', 30),
  ('collectibles', 'Collectibles', 'Rare, vintage, and collectible goods.', 40),
  ('vehicles', 'Vehicles', 'Cars, bikes, parts, and mobility products.', 50),
  ('services', 'Services', 'Local and remote professional services.', 60)
on conflict (slug) do update
set name = excluded.name,
    description = excluded.description,
    sort_order = excluded.sort_order,
    updated_at = now();

commit;
